-- VHDL wrapper for NiFpgaAG_fpga_top
-- Generated by LabVIEW FPGA IP Export Utility
--
-- Ports:
-- reset      :  Reset port. Minimum assertion length: 1 base clock cycles.
--               Minimum de-assertion length: 40 base clock cycles.
-- enable_in  :  Enable in port. Minimum re-initialization length: 7 base clock cycles.
-- enable_out :  Enable out port.
-- enable_clr :  Enable clear port.
-- ctrlind_00_d : Top level control "d", sync to Clk40, bool
-- ctrlind_01_d_latched : Top level indicator "d_latched", sync to Clk40, bool
-- ctrlind_02_c : Top level control "c", sync to Clk40, bool
-- ctrlind_03_c_echo : Top level indicator "c_echo", sync to Clk40, bool
-- ctrlind_04_b : Top level control "b", sync to Clk40, bool
-- ctrlind_05_a : Top level control "a", sync to Clk40, bool
-- ctrlind_06_a_and_b : Top level indicator "a_and_b", sync to Clk40, bool
-- ctrlind_07_a_or_b : Top level indicator "a_or_b", sync to Clk40, bool
-- Clk40 : Clock "40 MHz Onboard Clock", nominal frequency 40.00 MHz, base clock

library ieee;
use ieee.std_logic_1164.all;

entity NiFpgaIPWrapper_fpga_top is
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_d : in std_logic_vector(0 downto 0);
			ctrlind_01_d_latched : out std_logic_vector(0 downto 0);
			ctrlind_02_c : in std_logic_vector(0 downto 0);
			ctrlind_03_c_echo : out std_logic_vector(0 downto 0);
			ctrlind_04_b : in std_logic_vector(0 downto 0);
			ctrlind_05_a : in std_logic_vector(0 downto 0);
			ctrlind_06_a_and_b : out std_logic_vector(0 downto 0);
			ctrlind_07_a_or_b : out std_logic_vector(0 downto 0);
			Clk40 : in std_logic
		);
end NiFpgaIPWrapper_fpga_top;

architecture vhdl_labview of NiFpgaIPWrapper_fpga_top is

	component NiFpgaAG_fpga_top
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_d : in std_logic_vector(0 downto 0);
			ctrlind_01_d_latched : out std_logic_vector(0 downto 0);
			ctrlind_02_c : in std_logic_vector(0 downto 0);
			ctrlind_03_c_echo : out std_logic_vector(0 downto 0);
			ctrlind_04_b : in std_logic_vector(0 downto 0);
			ctrlind_05_a : in std_logic_vector(0 downto 0);
			ctrlind_06_a_and_b : out std_logic_vector(0 downto 0);
			ctrlind_07_a_or_b : out std_logic_vector(0 downto 0);
			Clk40 : in std_logic;
			tDiagramEnableOut : in std_logic
		);
	end component;

begin
	MyLabVIEWIP : NiFpgaAG_fpga_top
		port map(
			reset => reset,
			enable_in => enable_in,
			enable_out => enable_out,
			enable_clr => enable_clr,
			ctrlind_00_d => ctrlind_00_d,
			ctrlind_01_d_latched => ctrlind_01_d_latched,
			ctrlind_02_c => ctrlind_02_c,
			ctrlind_03_c_echo => ctrlind_03_c_echo,
			ctrlind_04_b => ctrlind_04_b,
			ctrlind_05_a => ctrlind_05_a,
			ctrlind_06_a_and_b => ctrlind_06_a_and_b,
			ctrlind_07_a_or_b => ctrlind_07_a_or_b,
			Clk40 => Clk40,
			tDiagramEnableOut => '1'
		);

end vhdl_labview;

